namespace AiOperationsHub.Application.Abstractions.Providers
{
    /// <summary>
    /// Represents a normalized response returned by an AI provider implementation.
    /// </summary>
    public sealed class AiProviderResponse
    {
        /// <summary>
        /// Gets or sets the primary text output returned by the AI provider.
        /// </summary>
        public string OutputText { get; set; } = null!;

        /// <summary>
        /// Gets or sets the raw serialized response payload returned by the provider, when available.
        /// </summary>
        public string? RawResponseJson { get; set; }

        /// <summary>
        /// Gets or sets the number of prompt tokens used by the request.
        /// </summary>
        public int? PromptTokenCount { get; set; }

        /// <summary>
        /// Gets or sets the number of output tokens generated by the provider.
        /// </summary>
        public int? OutputTokenCount { get; set; }

        /// <summary>
        /// Gets or sets the total number of tokens reported by the provider.
        /// </summary>
        public int? TotalTokenCount { get; set; }

        /// <summary>
        /// Gets or sets the cumulative token count tracked by the application.
        /// </summary>
        public long? CumulativeTokenCount { get; set; }

        /// <summary>
        /// Gets or sets the percentage of the configured budget used by the current request.
        /// </summary>
        public decimal? RequestPercentOfBudget { get; set; }

        /// <summary>
        /// Gets or sets the percentage of the configured budget used cumulatively.
        /// </summary>
        public decimal? CumulativePercentOfBudget { get; set; }
    }
}